### ISSUE TITLE
Fatal error: Uncaught Exception: 429 - TOO_MANY_REQUESTS 

### ISSUE THREAD

**Issue by vipera7** [netcap-agency/Seafile-API-to-PHP#1]
Hello,

I just installed your repo and started to test it. I have no error until I refresh the page I have the following error:

>  Fatal error: Uncaught Exception: 429 - TOO_MANY_REQUESTS - Server response status was: 429 with response: [{"detail":"Request was throttled. Expected available in 8.0 seconds."}] in E:\laragon\www\seafile\SeafileAPI.php:421 Stack trace: #0 E:\laragon\www\seafile\SeafileAPI.php(482): SeafileAPI->http_parse_message('{"detail":"Requ...') #1 E:\laragon\www\seafile\SeafileAPI.php(125): SeafileAPI->post('http://159.180....', Array) #2 E:\laragon\www\seafile\SeafileAPI.php(114): SeafileAPI->getToken() #3 E:\laragon\www\seafile\index.php(18): SeafileAPI->__construct(Array) #4 {main} thrown in E:\laragon\www\seafile\SeafileAPI.php on line 421

What it can be ?

**Comment by peacepostman** [comment]
Hello, my library is really old compared to recent release of Seafile. Unfortunately I dont use it anymore..  I suspect that some method changed is Seafile Core API, you should try an other library more updated, sorry to not have time to have a glance at it.. (https://github.com/rene-s/Seafile-PHP-SDK looks nice)

Have a nice day and thanks for  trying my lib :)

**Comment by vipera7** [comment]
Hey,

thank you for your fast response !
I will try using the lib you mentionned

Greeting for the new year :)
